#!/bin/bash


#####################################################################################################
#                                                                                                   #
#                    Script to make 50 commits and  pick one ramdom commit                          #
#                                                                                                   #
#####################################################################################################


#initializing git
git init

#########################################################################
#       crateing new file and making 50 commits                         #
#########################################################################

for commit_count in {1..50};

do

  fileName=$commit_count.txt
  echo "This is file number :- $commit_count" > $fileName 
  git add $fileName
  git commit -m"This is commit number $commit_count"

done


##########################################################################
#            picking one random commit from git log using awk            #
##########################################################################

#chosing random number between the range [1,50]
num=$(($((RANDOM%50))+1))

echo -e "\n=============================================================================\n"
echo -e "Printing any random commit . . . \n"
git log | awk -v num="$num" '
{ 
if ( num == $5 ){
  lines["message"] = $0;
  lines["hash"] = prev
}
if ($1 == "commit"){
  prev = $2;
}
}
END{ 
  print lines["message"] "==> " lines["hash"]
}'

echo -e "\n=============================================================================\n"

