#!/bin/bash

#####################################################################################################
#                                                                                                   #
#           Script to make 50 commits and print list of commits along with random commit            #                               
#                                                                                                   #
#####################################################################################################

#initializing git
git init

############################################################################
#       crateing new file and making 50 commits                            #
#       also adding some random sleep time between two succeccive commits  #
############################################################################

for commit_count in {1..50};

do

  fileName=$commit_count.txt
  echo "This is file number :- $commit_count" > $fileName 
  git add $fileName
  git commit -m"This is commit number $commit_count"
  
  #choosing random sleep time between 1 to 5 seconds
  sleepTime=$(($((RANDOM%4))+1))
  sleep $sleepTime

done


##########################################################################
#        Printing timeline of commits starting from first commit         # 
##########################################################################

echo -e "\n======================================================================\n"

# grep --> used for searching timeline 
# awk  --> used for output formatting 

git log --reverse | grep -e "Date" -e "commit"| \
    awk 'NR%3==0{gsub(/^[[:space:]]+/, "", $0);print $0 "["prev2 "]\n" prev1 "\n\n=====================================================================\n"} {if(NR%3==2) gsub(/commit /, "", prev1); prev2=prev1; prev1=$0;}'


